#!/usr/bin/env ruby

NAME       = File.basename($PROGRAM_NAME)
RAILS_ENV  = ENV.fetch("RAILS_ENV", "development")
RAILS_ROOT = File.join(File.dirname(__FILE__), "..")
SCRIPT_DIR = File.join(RAILS_ROOT,             "script")
LOG_FILE   = File.join(RAILS_ROOT,             *%W[log #{NAME}.log])
PID_FILE   = File.join(RAILS_ROOT,             *%W[tmp pids #{NAME}.pid])

if ARGV.shift.to_s.downcase == "stop"
  if pid = (File.read(PID_FILE).to_i rescue nil)
    puts "Stopping computer player (#{pid})..."
    begin
      Process.kill("INT", pid)
      puts "Stopped."
    rescue Exception => error
      puts "Could not stop: #{error.message}"
    end
  else
    puts "Computer player is not running."
  end
else
  puts "Starting computer player (#{Process.pid})..."
  ENV["RUBYLIB"] = File.expand_path(SCRIPT_DIR)
  ENV["WORKER_NAME"] = NAME
  production = RAILS_ENV == "production"
  stalk = "#{'/usr/local/ruby/bin/' if production}stalk"
  exec("#{stalk} worker Game.move#{" >>#{LOG_FILE} 2>&1" if production}")
end
